FIELDNAMES = ['URL', 'Query', 'Impressions', 'Clicks', 'Position']
DYNAMIC_FIELDNAMES = ['Impressions', 'Clicks', 'Position']
API_ROWS_LIMIT = 25000

COUNTRIES = {
    "abw": "Aruba",
    "afg": "Afghanistan",
    "ago": "Angola",
    "aia": "Anguilla",
    "ala": "Åland Islands",
    "alb": "Albania",
    "and": "Andorra",
    "are": "United Arab Emirates",
    "arg": "Argentina",
    "arm": "Armenia",
    "asm": "American Samoa",
    "ata": "Antarctica",
    "atf": "French Southern and Antarctic Lands",
    "atg": "Antigua and Barbuda",
    "aus": "Australia",
    "aut": "Austria",
    "aze": "Azerbaijan",
    "bdi": "Burundi",
    "bel": "Belgium",
    "ben": "Benin",
    "bes": "Caribbean Netherlands",
    "bfa": "Burkina Faso",
    "bgd": "Bangladesh",
    "bgr": "Bulgaria",
    "bhr": "Bahrain",
    "bhs": "The Bahamas",
    "bih": "Bosnia and Herzegovina",
    "blm": "Saint Barthélemy",
    "blr": "Belarus",
    "blz": "Belize",
    "bmu": "Bermuda",
    "bol": "Bolivia",
    "bra": "Brazil",
    "brb": "Barbados",
    "brn": "Brunei",
    "btn": "Bhutan",
    "bvt": "Bouvet Island",
    "bwa": "Botswana",
    "caf": "Central African Republic",
    "can": "Canada",
    "cck": "Cocos (Keeling) Islands",
    "che": "Switzerland",
    "chl": "Chile",
    "chn": "China",
    "civ": "Ivory Coast",
    "cmr": "Cameroon",
    "cod": "Democratic Republic of the Congo",
    "cog": "Republic of the Congo",
    "cok": "Cook Islands",
    "col": "Colombia",
    "com": "Comoros",
    "cpv": "Cabo Verde",
    "cri": "Costa Rica",
    "cub": "Cuba",
    "cuw": "Curaçao",
    "cxr": "Christmas Island",
    "cym": "Cayman Islands",
    "cyp": "Cyprus",
    "cze": "Czech Republic",
    "deu": "Germany",
    "dji": "Djibouti",
    "dma": "Dominica",
    "dnk": "Denmark",
    "dom": "Dominican Republic",
    "dza": "Algeria",
    "ecu": "Ecuador",
    "egy": "Egypt",
    "eri": "Eritrea",
    "esh": "Western Sahara",
    "esp": "Spain",
    "est": "Estonia",
    "eth": "Ethiopia",
    "fin": "Finland",
    "fji": "Fiji",
    "flk": "Falkland Islands",
    "fra": "France",
    "fro": "Faroe Islands",
    "fsm": "Federated States of Micronesia",
    "gab": "Gabon",
    "gbr": "United Kingdom",
    "geo": "Georgia (country)",
    "ggy": "Bailiwick of Guernsey",
    "gha": "Ghana",
    "gib": "Gibraltar",
    "gin": "Guinea",
    "glp": "Guadeloupe",
    "gmb": "The Gambia",
    "gnb": "Guinea-Bissau",
    "gnq": "Equatorial Guinea",
    "grc": "Greece",
    "grd": "Grenada",
    "grl": "Greenland",
    "gtm": "Guatemala",
    "guf": "French Guiana",
    "gum": "Guam",
    "guy": "Guyana",
    "hkg": "Hong Kong",
    "hmd": "Heard Island and McDonald Islands",
    "hnd": "Honduras",
    "hrv": "Croatia",
    "hti": "Haiti",
    "hun": "Hungary",
    "idn": "Indonesia",
    "imn": "Isle of Man",
    "ind": "India",
    "iot": "British Indian Ocean Territory",
    "irl": "Republic of Ireland",
    "irn": "Iran",
    "irq": "Iraq",
    "isl": "Iceland",
    "isr": "Israel",
    "ita": "Italy",
    "jam": "Jamaica",
    "jey": "Jersey",
    "jor": "Jordan",
    "jpn": "Japan",
    "kaz": "Kazakhstan",
    "ken": "Kenya",
    "kgz": "Kyrgyzstan",
    "khm": "Cambodia",
    "kir": "Kiribati",
    "kna": "Saint Kitts and Nevis",
    "kor": "South Korea",
    "kwt": "Kuwait",
    "lao": "Laos",
    "lbn": "Lebanon",
    "lbr": "Liberia",
    "lby": "Libya",
    "lca": "Saint Lucia",
    "lie": "Liechtenstein",
    "lka": "Sri Lanka",
    "lso": "Lesotho",
    "ltu": "Lithuania",
    "lux": "Luxembourg",
    "lva": "Latvia",
    "mac": "Macau",
    "maf": "Collectivity of Saint Martin",
    "mar": "Morocco",
    "mco": "Monaco",
    "mda": "Moldova",
    "mdg": "Madagascar",
    "mdv": "Maldives",
    "mex": "Mexico",
    "mhl": "Marshall Islands",
    "mkd": "North Macedonia",
    "mli": "Mali",
    "mlt": "Malta",
    "mmr": "Myanmar",
    "mne": "Montenegro",
    "mng": "Mongolia",
    "mnp": "Northern Mariana Islands",
    "moz": "Mozambique",
    "mrt": "Mauritania",
    "msr": "Montserrat",
    "mtq": "Martinique",
    "mus": "Mauritius",
    "mwi": "Malawi",
    "mys": "Malaysia",
    "myt": "Mayotte",
    "nam": "Namibia",
    "ncl": "New Caledonia",
    "ner": "Niger",
    "nfk": "Norfolk Island",
    "nga": "Nigeria",
    "nic": "Nicaragua",
    "niu": "Niue",
    "nld": "Netherlands",
    "nor": "Norway",
    "npl": "Nepal",
    "nru": "Nauru",
    "nzl": "New Zealand",
    "omn": "Oman",
    "pak": "Pakistan",
    "pan": "Panama",
    "pcn": "Pitcairn Islands",
    "per": "Peru",
    "phl": "Philippines",
    "plw": "Palau",
    "png": "Papua New Guinea",
    "pol": "Poland",
    "pri": "Puerto Rico",
    "prk": "North Korea",
    "prt": "Portugal",
    "pry": "Paraguay",
    "pse": "State of Palestine",
    "pyf": "French Polynesia",
    "qat": "Qatar",
    "reu": "Réunion",
    "rou": "Romania",
    "rus": "Russia",
    "rwa": "Rwanda",
    "sau": "Saudi Arabia",
    "sdn": "Sudan",
    "sen": "Senegal",
    "sgp": "Singapore",
    "sgs": "South Georgia and the South Sandwich Islands",
    "shn": "Saint Helena, Ascension and Tristan da Cunha",
    "sjm": "Svalbard and Jan Mayen",
    "slb": "Solomon Islands",
    "sle": "Sierra Leone",
    "slv": "El Salvador",
    "smr": "San Marino",
    "som": "Somalia",
    "spm": "Saint Pierre and Miquelon",
    "srb": "Serbia",
    "ssd": "South Sudan",
    "stp": "São Tomé and Príncipe",
    "sur": "Suriname",
    "svk": "Slovakia",
    "svn": "Slovenia",
    "swe": "Sweden",
    "swz": "Eswatini",
    "sxm": "Sint Maarten",
    "syc": "Seychelles",
    "syr": "Syria",
    "tca": "Turks and Caicos Islands",
    "tcd": "Chad",
    "tgo": "Togo",
    "tha": "Thailand",
    "tjk": "Tajikistan",
    "tkl": "Tokelau",
    "tkm": "Turkmenistan",
    "tls": "East Timor",
    "ton": "Tonga",
    "tto": "Trinidad and Tobago",
    "tun": "Tunisia",
    "tur": "Turkey",
    "tuv": "Tuvalu",
    "twn": "Taiwan",
    "tza": "Tanzania",
    "uga": "Uganda",
    "ukr": "Ukraine",
    "umi": "United States Minor Outlying Islands",
    "ury": "Uruguay",
    "usa": "United States",
    "uzb": "Uzbekistan",
    "vat": "Vatican City",
    "vct": "Saint Vincent and the Grenadines",
    "ven": "Venezuela",
    "vgb": "British Virgin Islands",
    "vir": "United States Virgin Islands",
    "vnm": "Vietnam",
    "vut": "Vanuatu",
    "wlf": "Wallis and Futuna",
    "wsm": "Samoa",
    "yem": "Yemen",
    "zaf": "South Africa",
    "zmb": "Zambia",
    "zwe": "Zimbabwe"
}